### ISSUE TITLE
Better error handling when parsing disco doc

### ISSUE THREAD

**Issue by leastprivilege** [DuendeArchive/IdentityModel.OidcClient.Old#1]
Some values are mandatory - and just throw nullrefex if not present.

**Comment by luisgoncalves** [comment]
I was just testing the lib with Google's implementation and came across this issue (or similar). Google's JWTs don't include the `nbf` claim, which is correct, since it is [marked as optional on the JWT spec](https://tools.ietf.org/html/rfc7519#section-4.1.5) and OpenID Connect [doesn't mention it](http://openid.net/specs/openid-connect-core-1_0.html#IDToken). I guess this one should only be processed if present.

I might get into this after I take further look into the code. Nice job, btw :)

**Comment by leastprivilege** [comment]
done
