### ISSUE TITLE
Use "kid" parameter to select the ID token validation key

### ISSUE THREAD

**Issue by luisgoncalves** [DuendeArchive/IdentityModel.OidcClient.Old#12]
At the moment the first key in the keyset is always selected:

```
var e = Base64Url.Decode(providerInformation.KeySet.Keys.First().E);
var n = Base64Url.Decode(providerInformation.KeySet.Keys.First().N);
```

**Comment by luisgoncalves** [comment]
@leastprivilege the token header contains the "kid"; however, you're not opening the token, since this is done by jose-pcl. Maybe key selection could be handled by jose-pcl? Something like `JosePCL.Jwt.Decode(identityToken, kid => providerInformation.KeySet.Keys.First(k => k.Kid == kid));` ? The only problem I'm seeing is that `kid` is actually optional on the JWT header... Not sure how to gracefully handle that case.

**Comment by luisgoncalves** [comment]
@dvsekhvalnov: what are your thoughts on this?

**Comment by dvsekhvalnov** [comment]
Hey guys, you asking about this: https://github.com/dvsekhvalnov/jose-jwt#two-phase-validation ?

It can be quite easy ported to "small brother" from main library.

**Comment by luisgoncalves** [comment]
Exactly! Sorry I didn't look on the main lib. I was just wondering if the Decode method could have some friendly overload for this case, but the logic can as well be on OidcClient ID token validation. This also avoids the "key not found" problem on jose-pcl :)

**Comment by dvsekhvalnov** [comment]
Can do either way, method vs. callback. I personally like callback approach more (like https://github.com/dvsekhvalnov/jose2go#two-phase-validation)

because it is more "safe" if you will, as client of library you don't need to trust unverified data. Was never implemented in .net library though :)

Do you guys want to do it in jose-pcl or want me to implement it? I'm not sure i personally have ETA for the fix but i'm accepting patch requests. 

Anyway can you open ticket under: https://github.com/dvsekhvalnov/jose-pcl/issues ?

**Comment by leastprivilege** [comment]
done
