### ISSUE TITLE
What is ".well-known/openid-configuration"?

### ISSUE THREAD

**Issue by xperiandri** [DuendeArchive/IdentityModel.OidcClient.Old#37]
You added this and OpenIddict does not have such endpoint.
So app crashes at https://github.com/IdentityModel/IdentityModel.OidcClient/blob/master/src/Shared/ProviderInformation.cs#L40
What do I have to do if I don't have configuration endpoint on my server?

**Comment by brockallen** [comment]
> What is ".well-known/openid-configuration"

It's from the OIDC discovery spec: https://openid.net/specs/openid-connect-discovery-1_0.html

**Comment by leastprivilege** [comment]
I am pretty sure OpenIddict has that. Otherwise use IdentityServer ;)

**Comment by kevinchalet** [comment]
> I am pretty sure OpenIddict has that.

Indeed, it does (and it's enabled by default) :smile: 
Discovery is probably the best feature offered by OIDC, it would be criminal not to support it :smile: 

@xperiandri I'd say your issue is caused by something else (e.g you registered a non-HTTPS address in the OIDC client options and OpenIddict refused to serve your request). Try enabling logging to figure out what's causing the error you're seeing.

There's also probably some OIDC client options you can enable to debug the HTTP response.

**Comment by xperiandri** [comment]
What is the endpoint provided by OpenIddict for this? Do I have to enable it somewhere?

**Comment by kevinchalet** [comment]
> What is the endpoint provided by OpenIddict for this?

`/.well-known/openid-configuration`, as required by the OIDC discovery spec (the future OAuth2 discovery draft/spec will allow you to choose your own suffix, but with OIDC, the endpoint is defined by the spec).

> Do I have to enable it somewhere?

No, it's enabled by default.

**Comment by xperiandri** [comment]
Try `uwp` branch on my OpenIddict fork. Click `General` button
It crashes exactly at that call to `/.well-known/openid-configuration`
@leastprivilege, by the way, exception is absolutely undescriptive. I only figured out what happens when added sources from this repository to solution.

**Comment by leastprivilege** [comment]
@xperiandri then change it.

**Comment by xperiandri** [comment]
Add

``` C#
if (string.IsNullOrWhiteSpace(json))
    throw new InvalidOperationException("Cannot retrieve OpenID Connect configuration from /.well-known/openid-configuration
 endpoint");
```

to line 41 of
https://github.com/IdentityModel/IdentityModel.OidcClient/blob/master/src/Shared/ProviderInformation.cs#L40
?

**Comment by kevinchalet** [comment]
> Try uwp branch on my OpenIddict fork. Click General button
> It crashes exactly at that call to /.well-known/openid-configuration

I'm afraid it works fine on my machine (TM).

Here's what I get after updating to OidcClient 1.4.0 (using 1.1.0 will crash because of the `at_hash` bug you fixed in July):

![image](https://cloud.githubusercontent.com/assets/6998306/19056184/fa8c3adc-89c7-11e6-8ded-dc104774655c.png)

> Add
> 
> ```
> if (string.IsNullOrWhiteSpace(json))
>     throw new InvalidOperationException("Cannot retrieve OpenID Connect configuration from /.well-known/openid-configuration
>  endpoint");
> ```
> 
> to line 41 of
> https://github.com/IdentityModel/IdentityModel.OidcClient/blob/master/src/Shared/ProviderInformation.cs#L40
> ?

This won't work since `GetStringAsync` always throws for unsuccessful HTTP responses (your snippet would never be reached): https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpClient.cs#L172

Here's what we use in the OAuth2 social providers: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/dev/src/AspNet.Security.OAuth.Foursquare/FoursquareAuthenticationHandler.cs#L39-L47. The ASP.NET team has adopted a similar pattern for the OIDC middleware (coming in 1.1.0). 

@leastprivilege if you like this approach, I'd be happy to submit a PR :smile:

**Comment by leastprivilege** [comment]
Oh yea - using `GetString` is definitely wrong. Should be a combination of `GetAsync` and checking the response.

I might get to that soon - otherwise feel free to fix it via a PR.

**Comment by kevinchalet** [comment]
> I might get to that soon - otherwise feel free to fix it via a PR.

I don't want to interfere with your plans, specially if this fix is part of a bigger change.
Just fell free to ping me if you don't find the time to fix it yourself.

**Comment by leastprivilege** [comment]
Well - changing to GetAsync and properly checking the status code shouldn't interfere with anything. Do it when you have time - otherwise I will soon-ish.
